import Link from 'next/link'

export default function Home(){
 return <>
  <header className="site-nav"><div className="container nav-inner"><Link href="/" className="brand"><div className="brand-mark">c</div><div className="brand-copy"><strong>CorrigeAI</strong><span>Gestão e correção escolar</span></div></Link><nav className="nav-links"><a href="#recursos">Recursos</a><a href="#como-funciona">Como funciona</a><a href="#seguranca">Segurança</a><a href="#planos">Planos</a></nav><div className="nav-actions"><Link href="/login" className="btn btn-secondary">Entrar</Link><Link href="/cadastro" className="btn btn-primary">Começar agora</Link></div></div></header>
  <main>
   <section className="hero"><div className="container hero-grid"><div><div className="eyebrow">Para escolas e professores</div><h1>Mais controle sobre a avaliação. Menos trabalho operacional.</h1><p className="hero-copy">O CorrigeAI reúne provas, turmas, alunos, resultados e correção de folhas de respostas em um único ambiente profissional, pensado para a rotina escolar.</p><div className="hero-actions"><Link href="/cadastro" className="btn btn-primary btn-lg">Criar minha conta</Link><a href="#recursos" className="btn btn-secondary btn-lg">Conhecer recursos</a></div><div className="hero-note">Sem compromisso. Comece com uma demonstração da plataforma.</div></div>
     <div className="hero-panel"><div className="panel-head"><div className="panel-title">Visão geral da escola</div><span className="status-pill">Operação normal</span></div><div className="stat-rows"><div className="stat-row"><span className="stat-label">Alunos ativos</span><span className="stat-number">482</span></div><div className="stat-row"><span className="stat-label">Turmas</span><span className="stat-number">16</span></div><div className="stat-row"><span className="stat-label">Avaliações no período</span><span className="stat-number">28</span></div><div className="stat-row"><span className="stat-label">Correções concluídas</span><span className="stat-number">94%</span></div></div></div>
   </div></section>
   <section className="trust"><div className="container"><div className="trust-row"><span>PROVAS ORGANIZADAS</span><span>RESULTADOS CENTRALIZADOS</span><span>ROTINA ESCOLAR MAIS FLUIDA</span></div></div></section>
   <section id="recursos" className="section"><div className="container"><div className="section-head"><div><h2>Uma plataforma para a rotina inteira da avaliação.</h2><p>Da criação da prova ao resultado final, cada etapa fica registrada e organizada.</p></div></div><div className="features"><div className="feature-card"><div className="feature-number">01</div><h3>Provas e gabaritos</h3><p>Crie avaliações, organize questões e mantenha o gabarito vinculado à prova.</p><a className="feature-link" href="/provas">Ver módulo de provas →</a></div><div className="feature-card"><div className="feature-number">02</div><h3>Correção por foto</h3><p>Envie folhas de respostas e acompanhe o processamento da correção por imagem.</p><a className="feature-link" href="/correcao">Conhecer correção →</a></div><div className="feature-card"><div className="feature-number">03</div><h3>Resultados e relatórios</h3><p>Consulte notas, acertos, médias e desempenho por aluno, turma e disciplina.</p><a className="feature-link" href="/resultados">Ver resultados →</a></div></div></div></section>
   <section id="como-funciona" className="section section-soft"><div className="container"><div className="section-head"><div><h2>Da aplicação à análise, sem planilhas espalhadas.</h2><p>O fluxo foi desenhado para reduzir tarefas repetitivas e dar visibilidade para a equipe escolar.</p></div></div><div className="process"><div className="process-card"><span className="step">01</span><strong>Prepare</strong><p>Monte a prova e defina o gabarito antes da aplicação.</p></div><div className="process-card"><span className="step">02</span><strong>Corrija</strong><p>Envie a foto da folha e acompanhe o processamento.</p></div><div className="process-card"><span className="step">03</span><strong>Analise</strong><p>Consulte notas e indicadores para tomar decisões pedagógicas.</p></div></div></div></section>
   <section id="seguranca" className="section"><div className="container split"><div><div className="eyebrow">Controle e segurança</div><h2>Dados organizados para quem precisa tomar decisões.</h2><p className="hero-copy">Perfis de acesso, organização por escola e histórico centralizado ajudam a manter cada informação no lugar certo.</p><ul className="bullet-list"><li><span className="check">✓</span><span>Perfis de Professor, Coordenador e Diretor.</span></li><li><span className="check">✓</span><span>Turmas, alunos e avaliações organizados por contexto escolar.</span></li><li><span className="check">✓</span><span>Resultados centralizados para acompanhamento pedagógico.</span></li></ul></div><div className="proof-card"><p className="quote">“O objetivo não é substituir a decisão do professor. É devolver tempo para ele analisar o que realmente importa.”</p><div className="quote-by">Equipe CorrigeAI</div><div className="quote-role">Produto e experiência escolar</div></div></div></section>
   <section id="planos" className="section section-soft"><div className="container"><div className="section-head"><div><h2>Comece pelo que sua escola precisa.</h2><p>Planos pensados para diferentes tamanhos de operação.</p></div></div><div className="pricing"><div className="price-card"><div className="price-title">Professor</div><div className="price">Grátis</div><p>Para uso individual e demonstração da plataforma.</p><ul className="price-list"><li>Criação de provas</li><li>Turmas e alunos</li><li>Resultados básicos</li></ul><Link href="/cadastro" className="btn btn-secondary" style={{width:'100%'}}>Começar</Link></div><div className="price-card highlight"><div className="price-title">Escola</div><div className="price">Sob consulta</div><p>Para equipes que precisam centralizar a rotina de avaliação.</p><ul className="price-list"><li>Perfis por equipe</li><li>Correção por foto</li><li>Relatórios e acompanhamento</li></ul><Link href="/cadastro" className="btn btn-primary" style={{width:'100%'}}>Solicitar contato</Link></div><div className="price-card"><div className="price-title">Rede</div><div className="price">Personalizado</div><p>Para operações com múltiplas escolas e necessidades específicas.</p><ul className="price-list"><li>Estrutura multiunidade</li><li>Relatórios ampliados</li><li>Atendimento dedicado</li></ul><Link href="/cadastro" className="btn btn-secondary" style={{width:'100%'}}>Falar com a equipe</Link></div></div></div></section>
   <section className="cta"><div className="container"><div className="cta-box"><div><h2>Leve o CorrigeAI para a rotina da sua escola.</h2><p>Organize avaliações, reduza tarefas repetitivas e tenha mais clareza sobre os resultados.</p></div><Link href="/cadastro" className="btn btn-primary btn-lg">Começar agora</Link></div></div></section>
  </main>
  <footer className="footer"><div className="container"><div className="footer-grid"><div><Link href="/" className="brand"><div className="brand-mark">c</div><div className="brand-copy"><strong>CorrigeAI</strong><span>Gestão e correção escolar</span></div></Link><p style={{marginTop:14,maxWidth:280}}>Uma plataforma para organizar avaliações e tornar a correção mais eficiente.</p></div><div><h4>Produto</h4><a href="#recursos">Recursos</a><a href="#como-funciona">Como funciona</a><a href="#planos">Planos</a></div><div><h4>Empresa</h4><a href="#seguranca">Segurança</a><a href="/login">Acessar plataforma</a><a href="/cadastro">Criar conta</a></div><div><h4>Suporte</h4><p>Atendimento comercial</p><p>Suporte da plataforma</p></div></div><div className="footer-bottom">© 2026 CorrigeAI. Todos os direitos reservados.</div></div></footer>
 </>
}
