import { FormEvent, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api, setSession } from '../../services/api';
import '../Auth.css';

export default function Login(){
 const nav=useNavigate(); const [email,setEmail]=useState(''); const [senha,setSenha]=useState(''); const [loading,setLoading]=useState(false); const [erro,setErro]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setErro('');if(!email||!senha){setErro('Preencha e-mail e senha.');return;}setLoading(true);try{const d=await api.login(email,senha);setSession(d.token,d.usuario);nav('/dashboard');}catch(err){setErro(err instanceof Error?err.message:'Não foi possível entrar.');}finally{setLoading(false)}}
 return <div className="auth-page"><section className="auth-brand"><img src="/assets/logo-horizontal-branco.png" alt="CorrigeAI"/><div className="auth-brand-content"><span className="eyebrow">GESTÃO E AVALIAÇÃO ESCOLAR</span><h1>Menos tempo corrigindo. Mais tempo ensinando.</h1><p>Uma plataforma para organizar provas, turmas, alunos, resultados e a rotina de correção.</p></div><div className="auth-note">Acesso destinado a escolas e profissionais autorizados.</div></section><section className="auth-card-wrap"><div className="auth-card"><img src="/assets/logo-horizontal.png" alt="CorrigeAI"/><h2>Entrar</h2><p>Acesse sua conta do CorrigeAI.</p>{erro&&<div className="error-box">{erro}</div>}<form className="auth-form" onSubmit={submit}><div className="field"><label>E-mail</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="seu@email.com" autoComplete="email"/></div><div className="field"><label>Senha</label><input value={senha} onChange={e=>setSenha(e.target.value)} type="password" placeholder="Sua senha" autoComplete="current-password"/></div><button className="btn btn-dark auth-submit" disabled={loading}>{loading?'Entrando...':'Entrar'}</button></form><div className="auth-bottom"><span>Ainda não possui conta?</span><Link to="/cadastro">Criar conta</Link></div><div className="auth-bottom"><Link to="/">Voltar para o site</Link><span>Acesso seguro</span></div></div></section></div>
}
