import { useState } from 'react';
import { AppShell } from '../../components/AppShell';
import { Plus, Save, Trash2 } from 'lucide-react';
import '../Module.css';

export default function EditarProva(){
 const [qs,setQs]=useState([1,2,3,4]);
 return <AppShell><div className="container page"><div className="page-head"><div><h1 className="page-title">Editar prova</h1><p className="page-subtitle">Atualize as questões e o gabarito antes da publicação.</p></div><button className="btn btn-primary"><Save size={15}/> Salvar alterações</button></div><section className="card card-pad"><div className="form-grid"><div className="field"><label>Título</label><input defaultValue="Matemática — Função afim"/></div><div className="field"><label>Disciplina</label><select defaultValue="Matemática"><option>Matemática</option><option>Português</option><option>Ciências</option></select></div><div className="field"><label>Turma</label><select defaultValue="8º Ano A"><option>8º Ano A</option><option>8º Ano B</option></select></div><div className="field"><label>Data</label><input type="date" defaultValue="2026-09-10"/></div></div></section><div style={{height:16}}/>{qs.map(n=><section className="card card-pad" key={n} style={{marginBottom:14}}><div className="toolbar"><div><h3 className="card-title">Questão {n}</h3><p className="card-subtitle">Edite o conteúdo e mantenha o gabarito atualizado.</p></div><button className="icon-btn" onClick={()=>setQs(x=>x.filter(q=>q!==n))}><Trash2 size={14}/></button></div><div className="field"><label>Enunciado</label><textarea rows={2} defaultValue="Questão de função e interpretação de gráfico."/></div><div style={{height:12}}/><div className="form-grid">{['A','B','C','D','E'].map(l=><div className="field" key={l}><label>Alternativa {l}</label><input defaultValue={`${l} — alternativa`}/></div>)}</div><div style={{height:12}}/><div className="form-grid"><div className="field"><label>Resposta correta</label><select defaultValue={['B','C','A','D'][n-1]}><option>A</option><option>B</option><option>C</option><option>D</option><option>E</option></select></div><div className="field"><label>Valor</label><input type="number" defaultValue="1" step="0.1"/></div></div></section>)}<button className="btn" onClick={()=>setQs(x=>[...x,x.length+1])}><Plus size={15}/> Adicionar questão</button></div></AppShell>
}
